name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: my-app
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: package install
        run: npm ci
      - name: build
        run: npm run build
      - name: start
        run: npm run pm2 start
